### ISSUE TITLE
HostMetadata and HostMetadataItem 

### ISSUE THREAD

**Issue by b2ronn** [zabbix/zabbix-agent-chocolatey#15]
Please add possibility of change **HostMetadata** and **HostMetadataItem** via -params or something like this.

**Comment by KakersUK** [comment]
Hi,

This won't be possible as it's not a supported parameter of the MSI installer: https://www.zabbix.com/documentation/4.2/manual/installation/install_from_packages/win_msi.

It would first need to be listed as an available option by raising a feature request with the development team: https://support.zabbix.com/secure/Dashboard.jspa (I'm just a community member, free time and what not). As this is an optional parameter I don't really think they will add it.

If you're getting the problem with updates via the MSI method overwriting the config everytime due to upgrades, then I would recommend adding these variables to the zabbix_agentd.conf.d folder. The contents shouldn't be overwritten and you call it something like hostmetadata.conf.
