### ISSUE TITLE
Question: Diff between zabbix-agent and zabbix-agent.install

### ISSUE THREAD

**Issue by Fabian1976** [zabbix/zabbix-agent-chocolatey#22]
What is the difference between `zabbix-agent` and `zabbix-agent.install`?

**Comment by KakersUK** [comment]
- `zabbix-agent` is the orignal package made available on chocolatey in 2013 and harkens back to when there was only the Zip version.
- `zabbix-agent.install` came much later in 2019 once the MSI version became available. 

Arguably `zabbix-agent` should be the MSI version and the Zip version should be `zabbix-agent.portable`. However, as there are many more implementations of the Zip version I didn't want to break any existing setups, especially due to the sensitive nature of the product for sysadmins to monitor systems.

**Comment by Fabian1976** [comment]
Ok, thank you. I don't have an existing setup, so i will be using the `zabbix-agent.install` version. Tnx for the clarification.
